version: "2"
services:
  inception-v3:
    extends:
      file: docker-compose-basic.yml
      service: inception-v3

  artm-service:
    #build:
    #  args:
    #    - loglevel=0
    extends:
      file: docker-compose-basic.yml
      service: artm-service

  webapp:
    extends:
      file: docker-compose-basic.yml
      service: webapp
    volumes:
      - "./logs/webapp-dev-post.json:/var/log/webapp-post.json"
      - "./logs/webapp-dev-like.json:/var/log/webapp-like.json"
